spring.datasource.url=${DB_URL:jdbc:h2:mem:paymentdb}
spring.datasource.driverClassName=${DB_DRIVER:org.h2.Driver}
spring.datasource.username=${DB_USERNAME:sa}
spring.datasource.password=${DB_PASSWORD:password}

spring.jpa.database-platform=${JPA_DIALECT:org.hibernate.dialect.H2Dialect}
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}

spring.h2.console.enabled=${H2_CONSOLE_ENABLED:true}
spring.h2.console.path=/h2-console

management.endpoints.web.exposure.include=health,info